esphome:
  name: we2025
  friendly_name: WE2025

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "H97+CTDdL/M7dVeKmWWNcF9BWTpvMtd9mmYQF4ITvMA="

# Enable OTA updates (Fixed)
ota:
  platform: esphome

wifi:
  ssid: "WE4FA74E"
  password: "k9250585"

  # Enable fallback hotspot (captive portal) in case WiFi connection fails
  ap:
    ssid: "We2025 Fallback Hotspot"
    password: "4ISuH3KLL9DW"

captive_portal:


# Define GPIO outputs
output:
  - platform: gpio
    pin: GPIO4
    id: led_gpio4

  - platform: gpio
    pin: GPIO5
    id: led_gpio5

  - platform: gpio
    pin: GPIO12
    id: led_gpio12

  - platform: gpio
    pin: GPIO13
    id: led_gpio13

  - platform: gpio
    pin: GPIO14
    id: led_gpio14

  - platform: gpio
    pin: GPIO0
    id: led_gpio0

  - platform: gpio
    pin: GPIO2
    id: led_gpio2

  - platform: gpio
    pin: GPIO15
    id: led_gpio15

  - platform: gpio
    pin: GPIO16
    id: led_gpio16

  

# Expose LEDs as controllable lights in Home Assistant
light:
  - platform: binary
    output: led_gpio4
    name: "LED GPIO4"

  - platform: binary
    output: led_gpio5
    name: "LED GPIO5"

  - platform: binary
    output: led_gpio12
    name: "LED GPIO12"

  - platform: binary
    output: led_gpio13
    name: "LED GPIO13"

  - platform: binary
    output: led_gpio14
    name: "LED GPIO14"

  - platform: binary
    output: led_gpio0
    name: "LED GPIO0"

  - platform: binary
    output: led_gpio2
    name: "LED GPIO2"

  - platform: binary
    output: led_gpio15
    name: "LED GPIO15"

  - platform: binary
    output: led_gpio16
    name: "LED GPIO16"

#---------------------------------------------------------


